### ISSUE TITLE
5m KW Rocketry parts are available, but don't show up when size 4 (5m) selected

### ISSUE THREAD

**Issue by linuxgurugamer** [Crzyrndm/FilterExtension#46]
Subject says it all.  I have KW, and in career nothing showed up.  I went into a sandbox game, and only 2 parts showed up:  5m P-fairing base & 5m P-Fairing base expanded.  Nothing else.

**Comment by Kerbas-ad-astra** [comment]
Filter Extension doesn't know how big a part actually is -- it just puts them wherever they say they go.  To get sorted in the 5m part category, a part has to specify in its configuration that "bulkheadProfiles = size4" (or have size4 in the list of bulkheadProfiles).  This might be a job for your KW fixes.

**Comment by linuxgurugamer** [comment]
i see.  Ok, thanks, I'll take care of it in the patches

**Comment by Crzyrndm** [comment]
to be more correct, it's not so much that it doesn't know what size the part is (although tbh, that is fairly accurate), but the filter typically used is based on the bulkhead profiles property of the parts.

This is done for two reasons:
1) because generally speaking, it's more accurate and versatile than any other single property.
2) IIRC, stock follows the same principal

**Comment by linuxgurugamer** [comment]
Appreciate the support.  It turned out that most of KW's parts didn't have the bulkheadProfiles set, so I made up a set of patches to add it to all the parts that I could identify.

I've always wondered why the KW stuff never showed up, but wasn't inspired to look until someone reported a problem.

Thanks
